###################  spring配置  ###################
spring:
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static
      suffix: .html
  servlet:
      multipart:
        max-request-size: 100MB
        max-file-size: 100MB
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  freemarker:
    checkTemplateLocation: false

server.tomcat.access-log-enabled: true  #Tomcat access log配置

###################  项目启动端口  ###################
server:
  port: 888
  max-http-header-size: 10240
  tomcat:
    max-threads: 1024

###################  日志设置  ###################
#logging:
#  level: info,error
#  level.root: info
#  level.com.byxfd: debug
#  path: logs/
#  file: byxfd.log
